name: kedai_ayam_nina
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  go_router: ^17.2.2
  get_it: ^9.2.1
  flutter_bloc: ^9.1.1
  google_fonts: ^6.1.0
  firebase_core: ^4.7.0
  json_annotation: ^4.11.0
  dio: ^5.9.2
  firebase_auth: ^6.4.0
  image_picker: ^1.2.1
  equatable: ^2.0.8
  fl_chart: ^0.70.2
  bloc: ^9.2.0
  meta: ^1.17.0
  logger: ^2.7.0
  http_parser: ^4.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.14.1
  json_serializable: ^6.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/Logo-C1.png
  