// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzaHVSFL6zkkaump0AM1llBdnHLLiu5Kc',
    appId: '1:925519887542:web:79e1f56909db8420d1fa17',
    messagingSenderId: '925519887542',
    projectId: 'ayam-nina',
    authDomain: 'ayam-nina.firebaseapp.com',
    storageBucket: 'ayam-nina.firebasestorage.app',
    measurementId: 'G-67BYC8T5Q6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJt_LDVPyDfEsTERB6nNReNfvoHWttwvI',
    appId: '1:925519887542:android:7450d7e723898e4ad1fa17',
    messagingSenderId: '925519887542',
    projectId: 'ayam-nina',
    storageBucket: 'ayam-nina.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALmDRmudDeZidR3xQqjNzTQJewjpprr8g',
    appId: '1:925519887542:ios:737d039c9add6cd7d1fa17',
    messagingSenderId: '925519887542',
    projectId: 'ayam-nina',
    storageBucket: 'ayam-nina.firebasestorage.app',
    iosBundleId: 'com.example.kedaiAyamNina',
  );
}
